CREATE TABLE IF NOT EXISTS system_settings (
    id UUID PRIMARY KEY,
    namespace VARCHAR(32) NOT NULL UNIQUE,
    value_json JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
